name: Build Frontend Container

on:
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push Frontend to AWS ECR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install --ignore-scripts
        working-directory: ./Frontend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Log in to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPO }}

      - name: Build and tag Docker image
        run: |
              REPO_URI="${{ secrets.ECR_REPO }}"
              docker build -t backend:latest ./Frontend
              docker tag backend:latest $REPO_URI:frontend
    
      - name: Push Docker image to Amazon ECR
        run: |
              REPO_URI="${{ secrets.ECR_REPO }}"
              docker push $REPO_URI:frontend